### ISSUE TITLE
[Feature Req] Change pinecil settings in the app

### ISSUE THREAD

**Issue by anonymousaga** [lachlanbell/PineTool#1]
First I want to say that your app is really cool. As you said in the blog post, it is unnecessary, but how cool is it to show other maker friends a graph of your soldering iron temp?!?

Not sure if this is possible, but can the bluetooth be used to change settings of the pinecil?

This would be a game-changer. Using it on a battery? Just use your phone to change the settings. Because, unfortunately, 2 buttons and a tiny oled screen will always have a clunky interface.

Thanks :)

**Comment by lachlanbell** [comment]
Thank you for the suggestions! It would be possible to add a Pinecil settings view, and there's certainly no objections here to adding one. I'll look into it (free time permitting), though PRs are very welcome 😁
